[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "nmbrz"
version = "0.1-u"
authors = [
  { name="KaG9S", email="jokageorgik@gmail.com" },
]
description = "Improving calculations acuracy with Python. Smallest module for numbers!"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "Math :: calculations",
    "Operating System :: OS Independent"
]
license = "MIT"
license-files = ["LICENSE.md"]

[project.urls]
Homepage = "https://github.com/KaG9S/nmbrz"
Issues = "https://github.com/KaG9S/nmbrz/issues"

