[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nmbrz"
version = "v0.1"
requires-python = ">=3.8"
authors = [
  {name = "George", email = "jokageorgik@gmail.com"}
]
maintainers = [
  {name = "George", email = "jokageorgik@gmail.com"}
]
description = "Improving calculations acuracy with Python. Smallest module for numbers!"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE.md"]
keywords = ["nmbrz", "calculations"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Calculations"
  "Programming Language :: Python"
]

[project.urls]
Documentation = "https://github.com/KaG9S/nmbrz/md-files/DOCS.md"
Repository = "https://github.com/KaG9S/nmbrz"
Issues = "https://github.com/KaG9S/nmbrz/issues"
Changelog = "https://github.com/KaG9S/nmbrz/md-files/CHANGELOG.md"
